cinema/account/urls.py
from django.urls import path
from .views import signup

app_name = 'account'

urlpatterns = [
    path('signup/', signup, name='signup')
]

cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from cinema import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moviedb/', include('moviedb.urls')),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/moviedb/urls.py
from django.urls import path
from . import views

app_name = 'moviedb'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_movie/', views.create_movie, name='create_movie'),
    path('movie_details/<int:id>', views.movie_details, name='view'),
    path('edit_movie/<int:id>', views.edit_movie, name='edit'),
    path('delete_movie/<int:id>', views.delete_movie, name='delete')
]

cinema/moviedb/models.py
from django.db import models
from django.core.validators import MaxValueValidator

class ActorID(models.Model):
    idNum = models.IntegerField()

    def __str__(self):
        return str(self.idNum)

class Director(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Actor(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    idnum = models.OneToOneField(ActorID, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(verbose_name='Movie Description', null=True, blank=True)
    rating = models.IntegerField(default=0, null=True, blank=True, validators=[MaxValueValidator(10)])
    category = models.ManyToManyField(Category)
    cast = models.ManyToManyField(Actor)
    director = models.ForeignKey(Director, on_delete=models.CASCADE, null=True, blank=True)
    poster = models.ImageField(upload_to='movie/posters', null=True, blank=True)

cinema/moviedb/forms.py
from django.forms import ModelForm
from .models import Movie

class MovieForm (ModelForm):
    class Meta:
            model = Movie
            fields = '__all__'

cinema/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def signup(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect('login')

    return render(request, 'signup.html', context={'form': form})

cinema/moviedb/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import MovieForm
from .models import Movie

# Create your views here.
def index(request):
    movies = Movie.objects.all()

    return render(request, 'index.html', context={'movies': movies})


def create_movie(request):
    form = MovieForm()
    if request.method == 'POST':
            form = MovieForm(request.POST, files=request.FILES)

            if form.is_valid():
                form.save()
                return redirect('moviedb:index')

    return render(request, 'create_movie.html', context={'form': form})


def movie_details(request, id):
    movie = Movie.objects.get(pk=id)

    print(movie)
    return render(request, 'index.html', context={'movies':[movie]})

def edit_movie(request, id):
    movie = Movie.objects.get(pk=id)
    form = MovieForm(instance=movie)

    if request.method == 'POST':
        form = MovieForm(data=request.POST, instance=movie, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('moviedb:index')
        print('notvalid')

    return render(request, 'create_movie.html', context={'form': form})

def delete_movie(request, id):
    Movie.objects.get(pk=id).delete()

    return redirect('moviedb:index')

cinema/account/templates/signup.html
{% extends 'layout.html' %}

{% block title %}Login{% endblock %}


{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Register</button>
</form>
{% endblock %}

cinema/moviedb/templates/create_movie.html
{% extends 'layout.html' %}

{% block title %}
Create Movie
{% endblock %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %}

cinema/moviedb/templates/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block body %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Actors</th>
            <th scope="col">Rating</th>
            <th scope="col">Poster</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
        <tr>
            <td>{{ movie.id }}</td>
            <td>{{ movie.name }}</td>
            <td>{{ movie.description }}</td>
            <td>{% for cat in movie.category.all %}
                {{cat}}
                {% endfor %}
            </td>
            <td>
                {% for actor in movie.cast.all %}
                {{ actor }}
                {% endfor %}
            </td>
            <td>{{ movie.rating }}</td>
            <td>
                {% if movie.poster %}
                <img src="{{ movie.poster.url }}" />
                {% endif %}
            </td>
            <td>
                <a href="{% url 'moviedb:view' id=movie.id %}" class="btn btn-primary">View</a>
                <a href="{% url 'moviedb:edit' id=movie.id %}" class="btn btn-warning">Edit</a>
                <a href="{% url 'moviedb:delete' id=movie.id %}" class="btn btn-danger">Delete</a>
            </td>
            {% empty %}
            <td>No Movies Found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'moviedb:create_movie' %}" class="btn btn-success">Add</a>

{% endblock %}