iti_django/lab1/urls.py
from django.contrib import admin
from django.urls import path, include
from todo import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include(urls))
]

iti_django/todo/urls.py
from django.urls import path
from .views import index, view, edit, delete, movies

app_name = 'todo'

urlpatterns = [
    path('', index, name='index'),
    path('view/<int:todo_id>', view, name='view'),
    path('edit/<int:todo_id>', edit, name='edit'),
    path('delete/<int:todo_id>', delete, name='delete'),
    path('movies', movies, name='movies')
]

iti_django/todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

todos = [
    {
        "id": 1,
        "title": 'Read a book',
        "priority": 1,
        "description": "desc. 1: Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit"
    },
    {
        "id": 2,
        "title": 'Play a game',
        "priority": 3,
            "description": "desc. 2: Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit"
    },
    {
        "id": 3,
        "title": 'Watch a movie',
        "priority": 5,
            "description": "desc. 1: Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit"
    }
]

# Create your views here.
def index(request):
    # return HttpResponse("Hello, World!")
    return render(request, 'index.html', context={"todos":todos})


def view(request, todo_id):
    todo = filter(lambda todo: todo.get('id') == todo_id, todos)

    return render(request, 'index.html', context={"todos":todo})


def edit(request, todo_id):
    for index in range(len(todos)):
        if todos[index].get('id') == todo_id:
            todos[index]['description'] = "[UPDATED] " + todos[index]['description']
            break
    
    return redirect('/todo')


def delete(request, todo_id):
    for todo in todos:
        if todo.get('id') == todo_id:
            todos.remove(todo)

    return redirect('/todo')

def movies(request):
    return render(request, 'movies.html')

iti_django/templates/footer.html
<div>
    This is a footer
</div>

iti_django/templates/header.html
<div>
    <a href="{% url 'todo:index' %}">Todo</a>
    <a href="{% url 'todo:movies' %}">Movies</a>
</div>

iti_django/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo: {% block title%}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</head>

<body>
    {% include 'header.html' %}

    {% block body %}{% endblock %}

    {% include 'footer.html' %}
</body>

</html>

iti_django/todo/templates/index.html
{% extends 'layout.html' %}

{% block title %}
Home
{% endblock %}


{% block body %}
<h1>Todo</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Priority</th>
            <th scope="col">Description</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for todo in todos %}
        <tr>
            <th scope="row">{{ todo.id }}</th>
            <td>{{ todo.title }}</td>
            <td>{{ todo.priority }}</td>
            <td>{{ todo.description }}</td>
            <td>
                <a href="{% url 'todo:view' todo_id=todo.id %}" class="btn btn-primary">View</a>
                <a href="{% url 'todo:edit' todo_id=todo.id %}" class="btn btn-success">Update</a>
                <a href="{% url 'todo:delete' todo_id=todo.id %}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td>No Todos Found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

iti_django/todo/templates/movies.html
{% extends 'layout.html' %}
{% load get_data %}

{% block title %}
Movies
{% endblock %}


{% block body %}
{% get_movies_data as movies %}

<h1>Movies</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Year</th>
            <th scope="col">Type</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
        <tr>
            <th scope="row">{{ movie.imdbID }}</th>
            <td>{{ movie.Title }}</td>
            <td>{{ movie.Year }}</td>
            <td>{{ movie.Type }}</td>
        </tr>
        {% empty %}
        <tr>
            <td>No Todos Found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}